apiVersion: v1
kind: Service
metadata:
  name: conversao-distancia
spec:
  selector:
    app: conversao-distancia
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30000
  type: NodePort
